#pragma once
#define WM_SOCKET_MESSAGE (WM_USER + 1)
#define WM_CONTACT_MESSAGE (WM_USER + 2)
#define WM_LOGON_COMPLETED_MESSAGE (WM_USER + 3)
#define WM_ACCEPT_INCOMMING_CALL_MESSAGE (WM_USER + 4)
#define WM_RECEIVED_MESSAGE (WM_USER + 5)
#define WM_CREATE_INCOMMING_WINDOW_MESSAGE (WM_USER + 6)
#define WM_CREATE_OUTGOING_WINDOW_MESSAGE (WM_USER + 7)